export const GET_CATALOG_REQUEST = 'GET_CATALOG_REQUEST';
export const GET_CATALOG_SUCCESS = 'GET_CATALOG_SUCCESS';
export const GET_CATALOG_FAILURE = 'GET_CATALOG_FAILURE';

export const LOAD_MORE_REQUEST = 'LOAD_MORE_REQUEST';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_QTY_ITEM = 'ADD_QTY_ITEM';
export const MINUS_QTY_ITEM = 'MINUS_QTY_ITEM';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const ADD_MANUFACTURER_TO_FILTER = 'ADD_MANUFACTURER_TO_FILTER';
export const REMOVE_MANUFACTURER_FROM_FILTER = 'REMOVE_MANUFACTURER_FROM_FILTER';

export const ORDER_BY_ASC = 'ORDER_BY_ASC';
export const ORDER_BY_DESC = 'ORDER_BY_DESC';
export const SORT_BY = 'SORT_BY';

export const SET_MAX_PRICE_FILTER = 'SET_MAX_PRICE_FILTER';
export const SET_MIN_PRICE_FILTER = 'SET_MIN_PRICE_FILTER';

export const ADD_FILTER_BY_RAM = 'ADD_FILTER_BY_RAM';
export const REMOVE_FILTER_BY_RAM = 'REMOVE_FILTER_BY_RAM';

export const ADD_FILTER_BY_INTERNAL_STORAGE = 'ADD_FILTER_BY_INTERNAL_STORAGE';
export const REMOVE_FILTER_BY_INTERNAL_STORAGE = 'REMOVE_FILTER_BY_INTERNAL_STORAGE';

export const ADD_FILTER_BY_BRAND = 'ADD_FILTER_BY_BRAND';
export const REMOVE_FILTER_BY_BRAND = 'REMOVE_FILTER_BY_BRAND';
export const ADD_FILTER_BY_PRICE = 'ADD_FILTER_BY_PRICE';
export const REMOVE_FILTER_BY_PRICE = 'REMOVE_FILTER_BY_PRICE';

export const SET_ORDER_BY = 'SET_ORDER_BY';
